"""add session_character and character_preset

Revision ID: 81b450196ddd
Revises: 013_fix_user_achievements_fk
Create Date: 2026-05-04 18:11:11.680132

Note:
    Spurious autogenerated changes (TEXT -> String type alterations on
    achievement_counts / user_achievements / users.language and a
    foreign-key drop on user_achievements) were removed manually per the
    spec 005 task review checklist (T006). Only the two new tables and their
    indexes are introduced here.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81b450196ddd"
down_revision: Union[str, None] = "013_fix_user_achievements_fk"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "character_preset",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("appearance_natural", sa.Text(), nullable=False),
        sa.Column("appearance_tags", sa.Text(), nullable=False),
        sa.Column("default_position", sa.String(length=16), nullable=False),
        sa.Column("tags_meta", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("character_preset", schema=None) as batch_op:
        batch_op.create_index("idx_character_preset_name", ["name"], unique=False)

    op.create_table(
        "session_character",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("slot_index", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("appearance_natural", sa.Text(), nullable=False),
        sa.Column("appearance_tags", sa.Text(), nullable=False),
        sa.Column("position", sa.String(length=16), nullable=False),
        sa.Column("source_preset_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_character", schema=None) as batch_op:
        batch_op.create_index(
            "idx_session_character_session_slot",
            ["session_id", "slot_index"],
            unique=False,
        )


def downgrade() -> None:
    with op.batch_alter_table("session_character", schema=None) as batch_op:
        batch_op.drop_index("idx_session_character_session_slot")
    op.drop_table("session_character")

    with op.batch_alter_table("character_preset", schema=None) as batch_op:
        batch_op.drop_index("idx_character_preset_name")
    op.drop_table("character_preset")
